let message_types = {
  1240: {
    '200': 'First Presentments',
    '205': 'Second Presentments, Full',
    '282': 'Second Presentments, Partial',
  },
  1442: {
    '450': 'First Chargeback, Full',
    '451': 'Arbitration Chargebacks, Full',
    '453': 'First Chargeback, Partial',
    '454': 'Arbitration Chargebacks, Partial',
  },
  1644: {
    '603': 'Retrieval Requests',
    '640': 'Currency Updates',
    '680': 'File Currency Summary',
    '685': 'Financial Position Detail',
    '688': 'Settlement Position Detail',
    '691': 'Message Exception',
    '693': 'Text Messages',
    '695': 'File Trailer',
    '696': 'Financial Detail Addendum (if required)',
    '697': 'File Header',
    '699': 'File Reject',
  },
  1740: {
    '700': 'Fee Collections, Customer-generated',
    '780': 'Fee Collections, Returns',
    '781': 'Fee Collections, Resubmissions',
    '782': 'Fee Collections, Arbitration Returns',
    '783': 'Fee Collections,  Generated by Mastercard',
  }
};

module.exports = function(mti, functionCode) {
  try {
    let data = message_types[mti][functionCode] || 'Unknown Message Type';
    return data;

  } catch (e){
    return 'Unknown Message Type';
  }
};
  